"""Protocol and archive-security tests for the non-GUI mirror helper."""

from __future__ import annotations

import base64
import hashlib
import importlib.util
import io
import json
import os
from pathlib import Path
import stat
import subprocess
import sys
import tarfile

from cryptography.hazmat.primitives.asymmetric.ed25519 import (
    Ed25519PrivateKey,
)
import pytest


ROOT = Path(__file__).resolve().parents[2]
HELPER_PATH = ROOT / "tools" / "headless_mirror_identity.py"
BOOTSTRAP_PATH = ROOT / "tools" / "cloudflare_bootstrap.py"
TUNNEL_PATH = ROOT / "tools" / "cloudflare_tunnel_bootstrap.py"
GATEWAY_PATH = ROOT / "tools" / "mirror_gateway.py"


def _load(name: str, path: Path):
    spec = importlib.util.spec_from_file_location(name, path)
    assert spec and spec.loader
    module = importlib.util.module_from_spec(spec)
    sys.modules[name] = module
    spec.loader.exec_module(module)
    return module


helper = _load("headless_mirror_identity_test", HELPER_PATH)
bootstrap = _load("headless_cloudflare_bootstrap_test", BOOTSTRAP_PATH)
tunnel = _load("headless_tunnel_bootstrap_test", TUNNEL_PATH)
gateway = _load("headless_mirror_gateway_test", GATEWAY_PATH)


def b64url(value: bytes) -> str:
    return base64.urlsafe_b64encode(value).decode().rstrip("=")


def public_key(private: Ed25519PrivateKey) -> str:
    from cryptography.hazmat.primitives import serialization

    return b64url(
        private.public_key().public_bytes(
            serialization.Encoding.Raw,
            serialization.PublicFormat.Raw,
        )
    )


@pytest.fixture()
def fake_age_tools(tmp_path):
    recipient = "age1" + "q" * 58
    secret = "AGE-SECRET-KEY-1" + "Q" * 58
    keygen = tmp_path / "age-keygen"
    keygen.write_text(
        f"""#!{sys.executable}
import pathlib
import sys
if "-o" in sys.argv:
    target = pathlib.Path(sys.argv[sys.argv.index("-o") + 1])
    target.write_text("# generated by test tool\\n{secret}\\n")
    raise SystemExit(0)
if "-y" in sys.argv:
    print("{recipient}")
    raise SystemExit(0)
raise SystemExit(2)
""",
        encoding="utf-8",
    )
    keygen.chmod(0o755)

    age = tmp_path / "age"
    age.write_text(
        f"""#!{sys.executable}
import pathlib
import sys
HEADER = b"age-encryption.org/v1\\n"
if "--encrypt" in sys.argv:
    target = pathlib.Path(sys.argv[sys.argv.index("--output") + 1])
    target.write_bytes(HEADER + sys.stdin.buffer.read())
    raise SystemExit(0)
if "--decrypt" in sys.argv:
    raw = pathlib.Path(sys.argv[-1]).read_bytes()
    if not raw.startswith(HEADER):
        raise SystemExit(2)
    sys.stdout.buffer.write(raw[len(HEADER):])
    raise SystemExit(0)
raise SystemExit(2)
""",
        encoding="utf-8",
    )
    age.chmod(0o755)
    return keygen, age, recipient, secret


@pytest.fixture()
def identity(tmp_path, fake_age_tools):
    keygen, age, recipient, secret = fake_age_tools
    state_dir = tmp_path / "identity"
    router_key = Ed25519PrivateKey.generate()
    response = helper.initialize_identity(
        state_dir,
        {
            "schemaVersion": 1,
            "type": "forkmesh.headless-mirror-identity-init",
            "nodeName": "mirror-two",
            "routerPublicKey": public_key(router_key),
            "allowedOrigins": ["https://mirror2.forkmesh.com"],
        },
        age_keygen_program=str(keygen),
    )
    return {
        "state_dir": state_dir,
        "age": age,
        "keygen": keygen,
        "router_key": router_key,
        "public": response,
        "recipient": recipient,
        "secret": secret,
    }


def helper_command(identity, mode):
    return [
        sys.executable,
        str(HELPER_PATH),
        "--state-dir",
        str(identity["state_dir"]),
        mode,
    ]


def test_init_is_owner_only_idempotent_and_never_emits_secrets(identity):
    state_dir = identity["state_dir"]
    assert stat.S_IMODE(state_dir.stat().st_mode) == 0o700
    for name in ("node-ed25519.pem", "age-identity.txt", "public.json"):
        path = state_dir / name
        assert stat.S_IMODE(path.stat().st_mode) == 0o600
    encoded = json.dumps(identity["public"])
    assert identity["secret"] not in encoded
    assert "PRIVATE KEY" not in encoded
    second = helper.initialize_identity(
        state_dir,
        {
            "schemaVersion": 1,
            "type": "forkmesh.headless-mirror-identity-init",
            "nodeName": "mirror-two",
            "routerPublicKey": public_key(identity["router_key"]),
            "allowedOrigins": ["https://mirror2.forkmesh.com"],
        },
        age_keygen_program=str(identity["keygen"]),
    )
    assert second == identity["public"]
    assert second["ageRecipient"] == identity["recipient"]


def test_tunnel_manifest_signer_matches_bootstrap_protocol(identity):
    unsigned = tunnel.unsigned_tunnel_manifest(
        hostname="mirror2.forkmesh.com",
        node_name="mirror-two",
        public_key=identity["public"]["nodePublicKey"],
        tunnel_id="5b3d02ad-0a1d-4edc-91b2-dfc130af44a7",
        generated_at="2026-07-23T20:00:00Z",
    )
    signer = bootstrap.MirrorManifestSigner(helper_command(identity, "manifest-sign"))
    signed = signer.sign(unsigned)
    checked = gateway.validate_manifest(
        signed,
        node="mirror-two",
        public_key=identity["public"]["nodePublicKey"],
        public_origin="https://mirror2.forkmesh.com",
    )
    assert checked is None
    signature = base64.urlsafe_b64decode(signed["signature"]["value"] + "==")
    payload = bootstrap.mirror_manifest_payload(signed)
    from cryptography.hazmat.primitives.asymmetric.ed25519 import (
        Ed25519PublicKey,
    )

    Ed25519PublicKey.from_public_bytes(
        base64.urlsafe_b64decode(identity["public"]["nodePublicKey"] + "=")
    ).verify(signature, payload)


def test_manifest_signer_rejects_unconfigured_origin(identity):
    unsigned = tunnel.unsigned_tunnel_manifest(
        hostname="attacker.example",
        node_name="mirror-two",
        public_key=identity["public"]["nodePublicKey"],
        tunnel_id="tunnel-id",
    )
    payload = bootstrap.mirror_manifest_payload(unsigned)
    with pytest.raises(helper.HelperError, match="not configured"):
        helper.sign_mirror_manifest(
            identity["state_dir"],
            {
                "schemaVersion": 1,
                "type": "forkmesh.mirror-endpoint-signing-request",
                "algorithm": "Ed25519",
                "encoding": "base64url-no-padding",
                "canonicalization": "forkmesh-json-sort-v1",
                "publicKey": identity["public"]["nodePublicKey"],
                "payloadBase64": b64url(payload),
                "payloadSha256": hashlib.sha256(payload).hexdigest(),
            },
        )


def test_gateway_health_and_router_protocols_are_key_pinned(identity):
    health = gateway.ExternalHealthSigner(
        helper_command(identity, "health-sign"),
        identity["public"]["nodePublicKey"],
    )
    message = "forkmesh-https-health-v1\nmirror-two\n0123456789abcdef\n1784840000000"
    health_signature = health.sign(message)
    assert len(base64.urlsafe_b64decode(health_signature + "==")) == 64

    verifier = gateway.ExternalCapabilityVerifier(
        helper_command(identity, "capability-verify"),
        identity["public"]["routerPublicKey"],
    )
    capability = (
        "forkmesh-masked-proxy-v1\nmirror-two\nGET\n"
        "/v1/repositories/forkmesh/forkmesh/git-info-refs\n"
        + hashlib.sha256(b"").hexdigest()
        + "\nrequest-id-123456\n1784840000000"
    )
    signature = b64url(identity["router_key"].sign(capability.encode("utf-8")))
    assert verifier.verify(capability, signature)
    wrong_key = Ed25519PrivateKey.generate()
    assert not verifier.verify(
        capability, b64url(wrong_key.sign(capability.encode("utf-8")))
    )


def _run(command, cwd=None):
    return subprocess.run(
        command,
        cwd=cwd,
        check=True,
        capture_output=True,
        text=True,
        env={
            "PATH": os.environ.get("PATH", ""),
            "LANG": "C",
            "LC_ALL": "C",
        },
    ).stdout.strip()


def make_bare_repository(tmp_path):
    source = tmp_path / "source"
    bare = tmp_path / "source.git"
    source.mkdir()
    _run(["git", "init", "-b", "main"], source)
    _run(["git", "config", "user.name", "ForkMesh test"], source)
    _run(["git", "config", "user.email", "test@example.invalid"], source)
    (source / "README.md").write_text("headless mirror\n", encoding="utf-8")
    _run(["git", "add", "README.md"], source)
    _run(["git", "commit", "-m", "initial"], source)
    _run(["git", "clone", "--bare", str(source), str(bare)])
    return bare


def test_seal_and_materialize_round_trip(identity, tmp_path):
    bare = make_bare_repository(tmp_path)
    encrypted = tmp_path / "forkmesh.age"
    metadata = helper.seal_repository(
        identity["state_dir"],
        {
            "schemaVersion": 1,
            "type": "forkmesh.repository-archive-seal",
            "sourceRepository": str(bare),
            "ciphertextPath": str(encrypted),
        },
        age_program=str(identity["age"]),
    )
    assert encrypted.read_bytes().startswith(helper.AGE_NATIVE_HEADER)
    assert stat.S_IMODE(encrypted.stat().st_mode) == 0o600
    assert metadata == {
        "ok": True,
        "scheme": "age-encrypted-tar-v1",
        "ciphertextSha256": hashlib.sha256(encrypted.read_bytes()).hexdigest(),
        "ciphertextBytes": encrypted.stat().st_size,
        "keyReference": identity["public"]["ageKeyReference"],
        "expectedRefsSha256": gateway.refs_sha256(bare),
    }
    destination = tmp_path / "runtime"
    destination.mkdir(mode=0o700)
    response = helper.materialize_repository(
        identity["state_dir"],
        {
            "schemaVersion": 1,
            "type": "forkmesh.repository-archive-materialize",
            "scheme": metadata["scheme"],
            "ciphertextPath": str(encrypted),
            "ciphertextSha256": metadata["ciphertextSha256"],
            "keyReference": metadata["keyReference"],
            "destination": str(destination),
        },
        age_program=str(identity["age"]),
    )
    assert response == {"ok": True, "repositoryPath": "repository.git"}
    materialized = destination / "repository.git"
    assert (
        _run(
            ["git", "--git-dir", str(materialized), "rev-parse", "--is-bare-repository"]
        )
        == "true"
    )
    assert gateway.refs_sha256(materialized) == metadata["expectedRefsSha256"]


def _malicious_tar(kind):
    stream = io.BytesIO()
    with tarfile.open(fileobj=stream, mode="w") as archive:
        root = tarfile.TarInfo("repository.git")
        root.type = tarfile.DIRTYPE
        archive.addfile(root)
        if kind == "traversal":
            item = tarfile.TarInfo("../escaped")
            item.size = 1
            archive.addfile(item, io.BytesIO(b"x"))
        elif kind == "symlink":
            item = tarfile.TarInfo("repository.git/HEAD")
            item.type = tarfile.SYMTYPE
            item.linkname = "/etc/passwd"
            archive.addfile(item)
        else:
            item = tarfile.TarInfo("repository.git/device")
            item.type = tarfile.CHRTYPE
            item.devmajor = 1
            item.devminor = 3
            archive.addfile(item)
    return stream.getvalue()


@pytest.mark.parametrize("kind", ["traversal", "symlink", "device"])
def test_materializer_rejects_traversal_links_and_devices(identity, tmp_path, kind):
    encrypted = tmp_path / f"{kind}.age"
    encrypted.write_bytes(helper.AGE_NATIVE_HEADER + _malicious_tar(kind))
    destination = tmp_path / f"runtime-{kind}"
    destination.mkdir(mode=0o700)
    with pytest.raises(helper.HelperError, match="archive"):
        helper.materialize_repository(
            identity["state_dir"],
            {
                "schemaVersion": 1,
                "type": "forkmesh.repository-archive-materialize",
                "scheme": "age-encrypted-tar-v1",
                "ciphertextPath": str(encrypted),
                "ciphertextSha256": hashlib.sha256(encrypted.read_bytes()).hexdigest(),
                "keyReference": identity["public"]["ageKeyReference"],
                "destination": str(destination),
            },
            age_program=str(identity["age"]),
        )
    assert list(destination.iterdir()) == []
    assert not (tmp_path / "escaped").exists()


def test_operator_only_payloads_match_worker_canonicals(identity):
    node_private = helper._load_node_key(identity["state_dir"])
    node_public = node_private.public_key()
    reclaim = helper.sign_account_reclaim(
        identity["state_dir"],
        {
            "schemaVersion": 1,
            "type": "forkmesh.account-reclaim-signing",
            "nodeName": "mirror-two",
            "linkCode": "123456",
        },
        clock_ms=lambda: 1784840000000,
    )
    reclaim_payload = (
        "forkmesh-reclaim-node-v1\nmirror-two\n"
        + identity["public"]["nodePublicKey"]
        + "\n123456\n1784840000000"
    ).encode()
    node_public.verify(base64.urlsafe_b64decode(reclaim["sig"] + "=="), reclaim_payload)

    registration = helper.sign_endpoint_registration(
        identity["state_dir"],
        {
            "schemaVersion": 1,
            "type": "forkmesh.https-endpoint-registration-signing",
            "node": "mirror-two",
            "baseUrl": "https://mirror2.forkmesh.com",
        },
        clock_ms=lambda: 1784840000001,
    )
    registration_payload = (
        "forkmesh-https-endpoint-v1\nmirror-two\n"
        "https://mirror2.forkmesh.com\n"
        + identity["public"]["nodePublicKey"]
        + "\n1784840000001"
    ).encode()
    node_public.verify(
        base64.urlsafe_b64decode(registration["signature"] + "=="),
        registration_payload,
    )

    state_hash = hashlib.sha256(b"refs").hexdigest()
    record = helper.sign_catalog_v2(
        identity["state_dir"],
        {
            "schemaVersion": 1,
            "type": "forkmesh.catalog-v2-publication-signing",
            "record": {
                "owner": "forkmesh",
                "name": "forkmesh",
                "visibility": "public",
                "description": "Living code city \N{SNOWMAN}",
                "updatedAt": "1784840000002",
                "stateHash": state_hash,
            },
        },
    )
    state_payload = (
        "forkmesh-repostate-v1\nforkmesh\nforkmesh\n" + state_hash + "\n1784840000002"
    ).encode()
    node_public.verify(
        base64.urlsafe_b64decode(record["stateSig"] + "=="), state_payload
    )
    normalized = dict(record)
    catalog_signature = normalized.pop("catalogSig")
    assert normalized.pop("catalogSigVersion") == 2
    # Worker catalog-v2 verification removes this retained legacy-v1 field.
    assert normalized.pop("signature") == ""
    record_hash = hashlib.sha256(
        json.dumps(normalized, sort_keys=True, separators=(",", ":")).encode()
    ).hexdigest()
    node_public.verify(
        base64.urlsafe_b64decode(catalog_signature + "=="),
        ("forkmesh-catalog-v2\n" + record_hash).encode(),
    )


def test_unsafe_state_permissions_fail_closed(identity):
    public_state = identity["state_dir"] / "public.json"
    public_state.chmod(0o640)
    with pytest.raises(helper.HelperError, match="unsafe"):
        helper.verify_router_capability(identity["state_dir"], {})


def test_cli_surface_has_no_private_material_arguments_or_responses(identity):
    help_text = subprocess.run(
        [sys.executable, str(HELPER_PATH), "--help"],
        check=True,
        capture_output=True,
        text=True,
    ).stdout.lower()
    assert "--private" not in help_text
    assert "--seed" not in help_text
    assert "--secret" not in help_text
    info = subprocess.run(
        helper_command(identity, "public-info"),
        check=True,
        capture_output=True,
        text=True,
    ).stdout
    assert identity["secret"] not in info
    assert "PRIVATE KEY" not in info
    assert not any(
        key in json.loads(info)
        for key in ("privateKey", "seed", "secret", "credential", "token")
    )


def test_child_process_environment_is_an_explicit_non_secret_allowlist(
    monkeypatch,
):
    monkeypatch.setenv("CLOUDFLARE_API_TOKEN", "cloudflare-secret")
    monkeypatch.setenv("AWS_ACCESS_KEY_ID", "cloud-access-id")
    monkeypatch.setenv("SSH_AUTH_SOCK", "/private/agent.sock")
    environment = helper._safe_environment()
    assert set(environment) == {"PATH", "LANG", "LC_ALL"}
    assert "cloudflare-secret" not in environment.values()
    assert "cloud-access-id" not in environment.values()
    assert "/private/agent.sock" not in environment.values()
